version: "3.7"
services:
   reactappserver:
    container_name: reactappserver
    build:
      context: .
      args:
        node_version: ${NODE_VERSION}
    volumes:
      - ./my-app:/var/app
      - node_modules:/var/app/node_modules
    working_dir: /var/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_FOR=dEVELOP
    ports: 
      - 3000:3000
      - 9229:9229
    command: npm start
volumes:
  node_modules: