version: '3.9'
services:

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     - test
  mysql:
    build:
      args:
        mysqlVersion: ${MYSQL_VERSION}
      context: .
      dockerfile: Dockerfiles/mysql.Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    entrypoint:
      - bash
      - /usr/src/TodoApp/Scripts/initDB.sh
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_db_pw
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pw
      MYSQL_USER: ${MYSQL_USER}
    networks:
      test:
    ports:
      - '3306:3306'
      # - '3306'
    secrets:
      - mysql_root_pw
      - mysql_db_pw
    volumes:
      - ./VsCodeConfigFolders/Mysql:/home/node/.vscode-server/
      - ./Mysql/Installation:/var/lib/mysql
      - ./Mysql/Database:/docker-entrypoint-initdb.d/
      - ./Mysql/Scripts:/usr/src/TodoApp/Scripts
      # - ./Mysql/Database:/usr/src/TodoApp/Database

    working_dir: /usr/src/TodoApp
     
  api:
    build:
      args:
        node_version: ${API_VERSION_PROM}
      context: .
      dockerfile: Dockerfiles/api.Dockerfile
      target: $MODE_NODE_SERVER
    container_name: api
    depends_on:
      - mysql
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      MYSQL_DB: ${MYSQL_DATABASE}
      MYSQL_PW: /run/secrets/mysql_db_pw
      MYSQL_USER: ${MYSQL_USER}
    # mem_limit: 2500m
    networks:
      test:
    ports:
      - 8000:8000 # server port
      - 9228:9228 # vscode port
      - 9100:9100 # prometheus client port
    secrets:
        - mysql_db_pw
    user: node
    volumes:
      - ./VsCodeConfigFolders/Server:/home/node/.vscode-server/
      - ./Server:/var/app/server
      - node_modules_api:/var/app/server/node_modules

    working_dir: /var/app/server
    # command: npm start

  react:
    build:
      args:
        node_version: ${REACT_VERSION}
      context: .
      dockerfile: Dockerfiles/react.Dockerfile
      target: $MODE_REACT_CLIENT
    container_name: react
    # command: npm start
    mem_limit: 2000m
    environment:
      # FAST_REFRESH: 'false'
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_FOR: dEVELOP
    links:
      - api
    networks:
      test:
    ports:
      - 3000:3000 # client port
      - 9229:9229 # vscode port
    user: node
    volumes:
      - ./VsCodeConfigFolders/Client:/home/node/.vscode-server/
      - ./Client:/var/app/client
      # - ./Server:/var/app/server
      - node_modules_cli:/var/app/client/node_modules
    # restart: always
    
    working_dir: /var/app/client
  
secrets:
  mysql_db_pw:
    file: ./Mysql/Passwords/${MYSQL_PW_FILE}
  mysql_root_pw:
    file: ./Mysql/Passwords/${MYSQL_PW_ROOT_FILE}

networks:
  test:
    driver: bridge
    name: test

volumes:
  node_modules_api:
  node_modules_cli:
  # Server:
