version: "3.7"
services:
  reactApp:
    container_name: reactApp
    image: node:14-alpine
    build:
      context: . 
    volumes:
      - ./reactApp/my-app:/var/app  
    working_dir: /var/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_YEEEEEEE=React
    ports: 
      - 3000:3000
      - 9229:9229
      # - 8080:8080
    command: npm start
    # command: npm run debug
