version: "3.9"

services:
  mysql_server:
    networks:
      test:
        aliases: 
          - mysqlDB

    container_name: mysql_server
    secrets:
      - mysql_root_pw
      - mysql_db_pw
    build:
      context: .
      dockerfile: mysql.Dockerfile
      args:
        mysqlVersion: ${MYSQL_VERSION}
    working_dir: /usr/src/TodoApp
    volumes:
      - ./Mysql/Installation:/var/lib/mysql
      - ./Mysql/Database:/docker-entrypoint-initdb.d/
      - ./Mysql/Scripts:/usr/src/TodoApp/Scripts
      # - ./Mysql/Database:/usr/src/TodoApp/DatabaÌse
    ports:
      - "3306:3306"
      # - "3306"
     
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pw
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_db_pw
    entrypoint:
      - bash
      - /usr/src/TodoApp/Scripts/initDB.sh
    command: --default-authentication-plugin=mysql_native_password

  reactapp_client:
    networks:
      test:
        aliases:
          - ReactApp

    container_name: reactappserver
    # restart: always

    build:
      target: $MODE_REACT_CLIENT
      context: .
      dockerfile: react.Dockerfile
      args:
        node_version: ${NODE_VERSION}
    volumes:
      - ./Client:/var/app/client
      - node_modules_cli:/var/app/client/node_modules
      - ./Server:/var/app/server
      
    working_dir: /var/app/client
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_FOR: dEVELOP

    ports:
      - 3000:3000
      - 9229:9229
    # command: npm start
 
  api_server:
    networks:
      test:
        aliases:
          - api_server
    
    container_name: api_server
    secrets:
        - mysql_db_pw
    build:
      target: $MODE_NODE_SERVER
      context: .
      dockerfile: api_server.Dockerfile
      args:
        node_version: ${NODE_VERSION}
    volumes:
      - ./Server:/var/app/server
      - node_modules_api:/var/app/server/node_modules
      - ./Mysql/Database:/var/app/db

    working_dir: /var/app/server
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_FOR: dEVELOP
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DB: ${MYSQL_DATABASE}
      MYSQL_PW: /run/secrets/mysql_db_pw
    ports:
      - 5000:5000
      - 9228:9229 
    # command: npm start
  
secrets:
  mysql_root_pw:
    file: ./Mysql/Passwords/${MYSQL_PW_ROOT_FILE}
  mysql_db_pw:
    file: ./Mysql/Passwords/${MYSQL_PW_FILE}

networks:
  test:
    name: test
    driver: bridge

volumes:
  node_modules_api:
  node_modules_cli:
  # Server:
