USE db_todo;

-- drop procedures
DROP PROCEDURE IF EXISTS INSERT_TASK;
DROP PROCEDURE IF EXISTS LOGICAL_DELETE_TASK;
DROP PROCEDURE IF EXISTS PHYSICAL_DELETE_TASK;
-- drop tables
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS PERSON;
