USE db_todo;

/* #region  drop */
DROP TABLE IF EXISTS TASK;


/* #endregion */


CREATE TABLE TASK(
  ID INT(7) NOT NULL AUTO_INCREMENT,
  DESCR CHAR(20) NOT NULL,
  EXPIRATION DATE,
  ACTIVED BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT RESTR_ID PRIMARY KEY(id)
);