USE db_todo;

CREATE TABLE TASK(
  ID INT(7) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` CHAR(20) NOT NULL,
  EXPIRATION DATE,
  ACTIVED BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT RESTR_ID PRIMARY KEY(id)
);