USE db_todo;

CREATE TABLE TASK(
  id INT(7) NOT NULL AUTO_INCREMENT,
  `description` CHAR(20) NOT NULL,
  expirationDate DATE,
  activated BOOLEAN DEFAULT TRUE NOT NULL,
  CONSTRAINT RESTR_ID PRIMARY KEY(id)
);
