USE db_todo;

CREATE PROCEDURE INSERT_TASK(
  IN _DESCRIPTION CHAR(20),
  IN _EXPIRATION DATE
) INSERT INTO 
    TASK (`DESCRIPTION`, EXPIRATION)
  VALUES
    (_DESCRIPTION, _EXPIRATION);

CREATE PROCEDURE LOGICAL_DELETE_TASK(
  IN _ID INT(4)
) UPDATE TASK SET ACTIVED=FALSE WHERE ID = _ID;


CREATE PROCEDURE PHYSICAL_DELETE_TASK(
  IN _ID INT(4)
) DELETE FROM TASK WHERE ID = _ID;
