USE db_todo;

/* #region  drop */
DROP PROCEDURE IF EXISTS INSERT_TASK;
DROP PROCEDURE IF EXISTS EXAMPLE;
DROP PROCEDURE IF EXISTS DELETE_TASK;
/* #endregion */

DELIMITER $$
  CREATE PROCEDURE INSERT_TASK(
    IN _DESCR CHAR(20),
    IN _EXPIRATION DATE
  ) BEGIN
    INSERT INTO
      TASK (DESCR, EXPIRATION)
    VALUES
      (_DESCR, _EXPIRATION);
  END $$

  CREATE PROCEDURE DELETE_TASK(
    IN _ID INT(4)
  ) BEGIN
    UPDATE TASK SET ACTIVED=FALSE WHERE ID = _ID;
  END $$

DELIMITER ;