global:
  scrape_interval:     10s
  evaluation_interval: 10s 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
    
  - job_name: 'cadvisor'
    scrape_interval: 20s
    scrape_timeout: 20s
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'api'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['api:9100']    

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']    

    #metrics_path: '/prometheus'
